version: "3.3"
services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

  webserver:
    container_name: webserver
    image: antonioanerao/laravel:9.47.0
    restart: always
    networks:
      - proxy
    ports:
      - "5173:5173"
    volumes:
      - laravel/:/laravel
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.livewire.rule=Host(`laravel.docker.localhost`)"
      - "traefik.http.routers.livewire.entrypoints=web"

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    container_name: mysql
    restart: always
    networks:
      - proxy
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    environment:
      - PMA_ARBITRARY=1

networks:
  proxy:

volumes:
  mysql:
  laravel:
    external: true